default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - goharbor/chartmuseum-photon:v2.7.0
  - goharbor/chartmuseum-photon:v2.7.0
  - goharbor/harbor-core:v2.7.0
  - goharbor/harbor-core:v2.7.0
  - goharbor/harbor-db:v2.7.0
  - goharbor/harbor-db:v2.7.0
  - goharbor/harbor-db:v2.7.0
  - goharbor/harbor-db:v2.7.0
  - goharbor/harbor-db:v2.7.0
  - goharbor/harbor-db:v2.7.0
  - goharbor/harbor-jobservice:v2.7.0
  - goharbor/harbor-jobservice:v2.7.0
  - goharbor/nginx-photon:v2.7.0
  - goharbor/nginx-photon:v2.7.0
  - goharbor/notary-server-photon:v2.7.0
  - goharbor/notary-server-photon:v2.7.0
  - goharbor/notary-signer-photon:v2.7.0
  - goharbor/notary-signer-photon:v2.7.0
  - goharbor/harbor-portal:v2.7.0
  - goharbor/harbor-portal:v2.7.0
  - goharbor/redis-photon:v2.7.0
  - goharbor/redis-photon:v2.7.0
  - goharbor/registry-photon:v2.7.0
  - goharbor/harbor-registryctl:v2.7.0
  - goharbor/registry-photon:v2.7.0
  - goharbor/harbor-registryctl:v2.7.0
  - goharbor/trivy-adapter-photon:v2.7.0
  - goharbor/trivy-adapter-photon:v2.7.0
