default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6
  - docker.io/grafana/grafana:11.2.1
  - quay.io/kiwigrid/k8s-sidecar:1.27.4
