default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - jacky06/kubez-ansible:v2.0.1
  - jacky06/kubez-ansible:v2.0.0
  - jacky06/kubez-ansible:v3.0.1
  - jacky06/kubez-ansible:v3.0.0

