default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - kubesphere/ks-apiserver:v3.4.1
  - kubesphere/ks-console:v3.4.1
  - kubesphere/ks-controller-manager:v3.4.1
