default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.8


images:
  - quay.io/prometheus-operator/prometheus-config-reloader:v0.77.1
  - harbor.cloud.pixiuio.com/pixiuio/prometheus:v2.54.1
